# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 84a327ad8016373e50dcc61776336bedc12bd1267ce373b3023aab837d538f7bd40d124d36223d56d3d5bfd6600a36a3fa894f9e23708554eadcc1082899a9d8

test:
  secret_key_base: cffad32da2b57cc7e211fd7e3f3ede3e6634025304ba4ea95fe3ac8f42f823d8425831fb4c3705475bb895e28e2de40c8eafc7732fdf0a467fd5ad14125f862b

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
